### PR TITLE
[2.0] Use two podspecs instead of one

### PR DESCRIPTION
**Pull request by dfed**
#37 didn't do what we needed. Going to 2 pod specs should do it.

CI will fail this PR, since we'll need to publish CoreAardvak before Aardvark will lint.

cc @justinseanmartin @pwesten @natan

### CODE REVIEW

**Comment by justinseanmartin** [comment]
I'd probably organize everything into two top level folders Core & Aardvark at the top level. That way you can just import everything under those two folders (makes the podspec a bit cleaner). That said, its also fine as is.

**Comment by justinseanmartin** [comment]
LGTM

**Comment by natan** [comment]
LGTM too.

**Comment by dfed** [comment]
Took @justinseanmartin's suggestion and did a little reorganization at the file level

**Comment by dfed** [comment]
Published CoreAardvark. CI should pass now.

**Pull request merged**
