### PR TITLE
README.md header formatting

### PR DESCRIPTION
**Pull request by edenman**
@shawnwelch

### CODE REVIEW

**Comment by dfed** [comment]
Thanks for the help cleaning up! The whole point is there are three steps... so I like the count. Not sure how this got screwed up :/

**Comment by edenman** [comment]
@dfed they still let you work on Square open source? :P

**Comment by dfed** [comment]
I still share ownership of the pod, and we all contribute :)

**Comment by dfed** [comment]
This was fixed with #44

**Pull request closed without merging**
