### PR TITLE
This is a catch all for this issue.

### PR DESCRIPTION
**Pull request by tkooger**
I don't know how you want to handle the error better.

### CODE REVIEW

**Comment by pwesten** [comment]
Hi Tim, it's definitely a good idea to catch exceptions that can be thrown by the NSFileHandle API. The question is on the best way to handle/recover, since a read/write failure means the ARKDataArchive would need to be tossed and re-created. Ideas?

**Comment by tkooger** [comment]
Well at this point I would hope that like all files that have been stored for the app; have been migrated over to new app folder. The ARKDataArchive is there to and can be accessed again normally. The app would only lose that last piece of data.

**Comment by pwesten** [comment]
Hm, I'm not sure how the migration case triggers this exception. The file URL is constructed relative to the app's applicationSupport in `-[ARKLogStore initWithPersistedLogFileName:...]`, so a change to the UUID of the app (between launches of course) shouldn't affect it. Is it possible that you have something deleting the entire contents of the application support directory at runtime?

**Comment by tkooger** [comment]
That would be when a new app is pushed to the client through mdm. It
deletes the old client and the new one uses a different guid.

On Wednesday, 17 February 2016, pwesten <notifications@github.com> wrote:

> Hm, I'm not sure how the migration case triggers this exception. The file
> URL is constructed relative to the app's applicationSupport in -[ARKLogStore
> initWithPersistedLogFileName:...], so a change to the UUID of the app
> (between launches of course) shouldn't affect it. Is it possible that you
> have something deleting the entire contents of the application support
> directory at runtime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/Aardvark/pull/33#issuecomment-185417000>.
>


-- 
Tim Kooger

The early bird may get the worm, but the second mouse gets the cheese.

**Comment by pwesten** [comment]
Oh, so are you saying that the entire app and its sandbox are deleted _while the app is running_?

**Comment by tkooger** [comment]
Ya in the older versions of iOS it used to kick you out of the app when an
update was installing it does not do that anymore so if an automatic
download of an updated app happens while you are using the app it will
eventually kick you out on install but at that point aardvark could be
trying to write to a file in the old app folder

On Wednesday, 17 February 2016, pwesten <notifications@github.com> wrote:

> Oh, so are you saying that the entire app and its sandbox are deleted *while
> the app is running*?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/Aardvark/pull/33#issuecomment-185455820>.
>


-- 
Tim Kooger

The early bird may get the worm, but the second mouse gets the cheese.

**Comment by pwesten** [comment]
If the process's files have been deleted out from underneath it, and it is microseconds away from being terminated, then I don't see the value of worrying about this particular failure case. At best, it will prevent a crash report from being saved. I'd consider it an iOS bug that they don't simply terminate the app _before_ deleting its sandbox.

**Comment by dfed** [comment]
Closing this due to lack of activity. If we encounter a concrete (customer-facing) situation with a valid recovery path, let's follow up with discussion in Issues.

**Pull request closed without merging**
