### PR TITLE
More accurate ARKDataArchive performance test

### PR DESCRIPTION
**Pull request by dfed**
cc @pwesten

### CODE REVIEW

**Comment by brianpartridge** [comment]
You're measurements include the truncation of old data, why not do that outside the measure block?

**Comment by dfed** [comment]
@brianpartridge the measure block is executed multiple times. There is no mechanism that I know of that allows you to clean up the environment between each measure block execution.

The tests currently don't test what they are intended to test. Take for example the appendLog test. On the second measure block, it is appending hundreds of logs to a data archive that already has hundreds of logs in it. Each measure block should start from a clean state. This adds to the overhead / time of each test, but at least now each test is starting with the same environment

**Comment by brianpartridge** [comment]
Right, and from the look of it, this is more accurate. But if we want it to be really correct, we should pre-populate a number of `ARKDataArchive`s in multiple locations in the file system so that the measure block can just have a fresh one vended each time. Then the rest of the test could just clean up what it setup.

**Comment by dfed** [comment]
Love that idea. Will investigate

**Comment by pwesten** [comment]
LGTM.

**Comment by dfed** [comment]
@brianpartridge unfortunately there's no way to guarantee that the `measureBlock` will run 10 times. It's not documented, and there's no variable you can inspect to see how many times it will run. For now I'm going to merge as-is, but will investigate preflighting an individual instance per measurement down the line.

**Comment by brianpartridge** [comment]
Sure. That's fine. It was already good as is, I was just hoping there was more we could do.

**Pull request merged**
