### PR TITLE
Fixed `CLANG_WARN_STRICT_PROTOTYPES` warnings in preparation for Xcode 9.

### PR DESCRIPTION
**Pull request by manolosavi**

### CODE REVIEW

**Comment by dfed** [comment]
Good find! Merging 🚀

**Comment by manolosavi** [comment]
Yeah we were updating our own code and noticed we had this issue here and in other third parties. Thanks for the super quick reply!

**Comment by dfed** [comment]
Will try to get a version bump out by Monday

**Comment by manolosavi** [comment]
Sounds good!

**Comment by dfed** [comment]
Latest release includes these changes!

**Pull request merged**
